### PR TITLE
feat: 🎸 Return all errors from body validation

### LINKED ISSUE #55: Should validation check all rules collecting all errors?
@jwalton What's the best way of returning all the errors when validating the request body. It feels like bad user experience to not respond with all the information available.

Would it be ok to just set `allErrors: true` in the `ajv` options by default?

### PR DESCRIPTION
**Pull request by niallmccullagh**
Return all the errors in the request body giving developers more detailed feedback on the validity of their request

Issues: Closes #55

### CODE REVIEW

**Comment by jwalton** [comment]
Actually, before I release this; I suppose the downside to this is that validation could be slower on a bad document with lots of errors.  Do we want to make "all errors" an option you pass in to exegesis?  My concern would be that if you pass in intentionally malformed documents you could keep the server busy with validation.

**Comment by jwalton** [comment]
I'm going to make that change.  :)

**Comment by niallmccullagh** [comment]
Are you going to make it a config value that can be set?

**Comment by jwalton** [comment]
Yeah, exactly.  I was thinking an `allErrors` option.

**Pull request merged**
