### PR TITLE
Fixes PluginsManager when plugin has no preRouting of postResponseVal…

### PR DESCRIPTION
**Pull request by an-mmx**
Fixes PluginsManager when plugin has no preRouting of postResponseValidation methods

### CODE REVIEW

**Comment by jwalton** [comment]
Good catch.  :P

Can you please change your commit message to follow conventional commit?  Something like:

```
fix(plugins): Fixes PluginsManager when plugin has no preRouting of postResponseValidation methods
```

**Comment by an-mmx** [comment]
Done

**Comment by jwalton** [comment]
Thanks.  This project uses semantic-release, so the "fix:" is what will cause a new release to be built and pushed to npm.  (I could have squash merged it, but then you wouldn't get a "contributor" status in this branch.  ;)

**Pull request merged**
